id: I4ACC0C26
source: ''
source_file: null
initial_creation_type: input
imported: '2022-06-29T10:11:20.550451'
last_modified: '2022-06-29T10:11:20.550534'
parser: null
source_metadata:
  creation_method: proof_reading
  source : 
    base_file:
      id: D3874/རྩ་བ།.txt
      initial_creation_type: input
  base:
    00A0:
      title: chonjuk root
      base_file: 00A0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
