id: I4ACC0C26
source: ''
source_file: null
initial_creation_type: input
imported: '2022-06-29T10:11:20.550451'
last_modified: '2022-06-29T10:11:20.550534'
parser: null
source_metadata: {}
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
